# fly.toml app configuration file generated for anime-schedules-spring-snowflake-1279 on 2024-02-02T17:05:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'anime-schedules-spring-snowflake-1279'
primary_region = 'gru'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION='pgsql'
  GOOGLE_CLIENT_ID='776060783697-7o47gse8jgk64c1ns1090cka8o9dk52c.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET='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'
  VITE_VAPID_PUBLIC_KEY='BBK_cdIHceBSw6FcG0ymZ7RBCASwf2cq549FOL6SZ0KXSnsGQmdYPoZL94NkGQ8BlCs5PM7GuK4eZF06zo2hny4'
  SENTRY_LARAVEL_DSN='https://e493641ff6a3a4ee4e2e581c544e7a4a@o450381.ingest.sentry.io/4506628643684352'
  JIKAN_API_URI='https://api.jikan.moe/v4'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[processes]
  app = ""
  cron = "cron -f"

[mounts]
  source="storage_vol"
  destination="/var/www/html/storage"
